export enum LOG_TYPE {
    EMERGENCY = 'EMERGENCY',
    ALERT = 'ALERT',
    CRITICAL = 'CRITICAL',
    ERROR = 'ERROR',
    WARNING = 'WARNING',
    NOTICE = 'NOTICE',
    INFO = 'INFO',
    DEBUG = 'DEBUG'
}